version: "3.9"

services:
  app:
    build: .
    container_name: pregnancy_app
    environment:
      DATABASE_URL: postgresql://ajiandrain:RaihanSecret1309@db:5432/pregnancy_guide_v2
    ports:
      - "8021:5000"
    networks:
      - postgres-docker_pg_network
    volumes:
      # Petakan folder model di dalam container ke volume bernama 'model_data'
      - model_data:/app/model_data 

volumes:
  model_data:

networks:
  postgres-docker_pg_network:
    external: true